### ISSUE TITLE
No stongholds are generated, /locate not working.

### ISSUE THREAD

**Issue by lenzls** [PG85/OpenTerrainGenerator#222]
Hello,

I'm playing for half a year now in a biome bundle world.
A few days ago, we realized that we can't find a stronghold with enderpearls. Then I double checked with `/locate stronghold` and the servers tells me then `Unable to locate any stronghold feature`

So it seems there are no strongholds generated in my world?

When I look at `<serverdir>/plugins/OpenTerrainGenerator/worlds/<biomebundle-world>/WorldConfig.ini`, I see the following lines:
```
[..]
###############
# Strongholds #
###############
StrongholdsEnabled: true
StrongholdCount: 128
StrongholdDistance: 32.0
StrongholdSpread: 3
[..]
```

So it seems regarding my configuration, it should generate strongholds.

Our server a normal Spigot 1.12.2. Plugins I'm using:
```
CleanroomGenerator.jar
CreeperHeal-7.0.5.jar
JourneyMapServer1.01_Bukkit_MC1.9.jar
MobCatcherLite.jar
Multiverse-Core-2.5.0.jar
Multiverse-NetherPortals-2.5.2-SNAPSHOT.jar
Multiverse-Portals-2.5.0.jar
'OpenTerrainGenerator-1.12.2 - v4.jar'
perworldinventory-1.11.1.jar
'SimpleFly - 1.1.jar'
worldedit-bukkit-6.1.7.3.jar
worldguard-6.2.1.jar
```

@MCPitman suggested to post this as a bug here and wondered if this could be something related to the multiverse plugin.

Therefore here is an excerpt of my `<serverdir>/plugins/Multiverse-Core/worlds.yml`. I removed all world except my biomebundle world and a vanilla world as an example.

```
worlds:
  biomebundle:
    ==: MVWorld
    hidden: 'false'
    alias: biomebundle
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -81.5
      y: 64.0
      z: -1327.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '-1855594102007842951'
    generator: OpenTerrainGenerator
    playerLimit: '-1'
    allowFlight: 'true'
  world:
    ==: MVWorld
    hidden: 'false'
    alias: world
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -85.0
      y: 80.0
      z: 377.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '3946264639521290473'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
[..]
```

What could go wrong here?
